dist: xenial
os: linux
language: python

before_install:
  - sudo wget https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
  - sudo dpkg -i pandoc-2.7.3-1-amd64.deb
  - pandoc --version

install:
  - pip install tox
  - pip install codecov

script:
  - tox -r

jobs:
    include:
        - python: 3.10
          env: TOXENV=py10
        - python: 3.11
          env: TOXENV=py11
        - python: 3.12
          env: TOXENV=py12
        - python: 3.13
          env: TOXENV=py313

        - python: 3.12
          env: TOXENV=style
        - python: 3.12
          env: TOXENV=coverage
        - python: 3.12
          env: TOXENV=docs
        - python: 3.12
          env: TOXENV=docstyle
        - python: 3.12
          env: TOXENV=check-manifest


after_success:
    - codecov --token=4022c5c1-b038-4f9b-bf1b-9d3b3d2b4628
