# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


env:
  default-python: "3.13"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - tox_env: py310
            python-version: "3.10"
          - tox_env: py311
            python-version: "3.11"
          - tox_env: py312
            python-version: "3.12"
          - tox_env: py313
            python-version: "3.13"
          - tox_env: style
            python-version: "3.13"
          - tox_env: check-manifest
            python-version: "3.13"
          - tox_env: coverage
            python-version: "3.13"
          - tox_env: docs
            python-version: "3.13"
            pandoc: true

    runs-on: ubuntu-latest

    # the steps of the CI
    steps:
      - uses: actions/checkout@master

      # optionals
      - name: Install pandoc
        if: ${{ matrix.pandoc }}
        run: sudo apt-get install pandoc

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version}}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest tox codecov # tox-gh-actions
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: tox -re ${{ matrix.tox_env }}
        run: tox -re ${{ matrix.tox_env }}

      # - name: Report coverage
      #   run: |
      #     tox -e coverage
      #     codecov --token=4022c5c1-b038-4f9b-bf1b-9d3b3d2b4628

